-- MySQL Script generated by MySQL Workbench
-- 03/18/15 19:48:15
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema FormationPPE
-- -----------------------------------------------------
-- Schéma relationnel de la base de données Formation de la Maison des Ligues.
CREATE SCHEMA IF NOT EXISTS `FormationPPE` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `FormationPPE` ;

-- -----------------------------------------------------
-- Table `FormationPPE`.`TypeEmploye`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FormationPPE`.`TypeEmploye` (
  `idTypeEmploye` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTypeEmploye`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FormationPPE`.`Employe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FormationPPE`.`Employe` (
  `idEmploye` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `mdp` CHAR(32) NOT NULL,
  `typeEmploye` INT NOT NULL,
  `superieur` INT NULL,
  PRIMARY KEY (`idEmploye`),
  INDEX `fk_Employe_TypeEmploye_idx` (`typeEmploye` ASC),
  INDEX `fk_Employe_Employe1_idx` (`superieur` ASC),
  CONSTRAINT `fk_Employe_TypeEmploye`
    FOREIGN KEY (`typeEmploye`)
    REFERENCES `FormationPPE`.`TypeEmploye` (`idTypeEmploye`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employe_Employe1`
    FOREIGN KEY (`superieur`)
    REFERENCES `FormationPPE`.`Employe` (`idEmploye`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FormationPPE`.`Prestataire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FormationPPE`.`Prestataire` (
  `idPrestataire` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `rue` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NULL,
  `codePostal` VARCHAR(10) NULL,
  PRIMARY KEY (`idPrestataire`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FormationPPE`.`Formation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FormationPPE`.`Formation` (
  `idFormation` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `duree` INT NOT NULL,
  `credit` INT NOT NULL,
  `idPrestataire` INT NOT NULL,
  PRIMARY KEY (`idFormation`),
  INDEX `fk_Formation_Prestataire1_idx` (`idPrestataire` ASC),
  CONSTRAINT `fk_Formation_Prestataire1`
    FOREIGN KEY (`idPrestataire`)
    REFERENCES `FormationPPE`.`Prestataire` (`idPrestataire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FormationPPE`.`Selectionner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FormationPPE`.`Selectionner` (
  `idEmploye` INT NOT NULL,
  `idFormation` INT NOT NULL,
  `etat` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmploye`, `idFormation`),
  INDEX `fk_Employe_has_Formation_Formation1_idx` (`idFormation` ASC),
  INDEX `fk_Employe_has_Formation_Employe1_idx` (`idEmploye` ASC),
  CONSTRAINT `fk_Employe_has_Formation_Employe1`
    FOREIGN KEY (`idEmploye`)
    REFERENCES `FormationPPE`.`Employe` (`idEmploye`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employe_has_Formation_Formation1`
    FOREIGN KEY (`idFormation`)
    REFERENCES `FormationPPE`.`Formation` (`idFormation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
